const ERROR_MESSAGE = {
  REQUIRED_EMAIL: "이메일은 필수 입력입니다.",
  REQUIRED_EMAIL_FORMAT: "이메일 형식으로 작성해 주세요.",
  DUPLICATE_EMAIL: "이미 사용중인 이메일입니다.",
  REQUIRED_NICKNAME: "닉네임은 필수 입력입니다.",
  NICKNAME_MAX_LENGTH: "닉네임은 최대 20자까지 가능합니다.",
  DUPLICATE_NICKNAME: "이미 사용중인 닉네임입니다.",
  REQUIRED_PASSWORD: "비밀번호는 필수 입력입니다.",
  REQUIRED_PASSWORD_FORMAT: "비밀번호는 숫자, 영문, 특수문자로만 가능합니다.",
  PASSWORD_MIN_LENGTH: "비밀번호는 최소 8자 이상입니다.",
  REQUIRED_PW_COMFIRMATION: "비밀번호 확인을 입력해주세요.",
  NOT_MATCH_PASSWORD: "비밀번호가 일치하지 않습니다.",
  DESCRIPTION_MIN_LENGTH: "상품 설명은 최소 10자 이상 입력해주세요.",
  DESCRIPTION_MAX_LENGTH: "상품 설명은 최대 300자 이하입니다.",
  REQUIRED_PRODUCT_NAME: "상품명은 필수 입력입니다.",
  REQUIRED_DESCRIPTION: "상품 설명은 필수 입력입니다.",
  REQUIRED_REVIEW: "리뷰 내용을 입력해주세요.",
  REVIEW_MIN_LENGTH: "리뷰는 최소 10자 이상 적어주세요.",
  REVIEW_MAX_LENGTH: "리뷰는 최대 500자까지 가능합니다.",
  REQUIRED_REVIEW_IMAGE: "리뷰 사진은 필수 입력입니다.",
  CHECK_EMAIL: "이메일을 확인해 주세요.",
  CHECK_PASSWORD: "비밀번호를 확인해 주세요.",
  PRODUCT_NAME: "상품 이름은 필수 입력입니다.",
  PRODUCT_MIN_LENGTH: "상품 이름은 최소 10자 이상입니다.",
  PRODUCT_MAX_LENGTH: "상품 이름은 최대 20자 이하입니다.",
};

export default ERROR_MESSAGE;
