import { Html, Head, Main, NextScript } from "next/document";

export default function Document() {
  return (
    <Html lang="ko">
      <title>MOGAZOA</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/icons/favicon.svg" />
      <Head />
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
