import Head from "next/head";
import HomeLayout from "@/src/components/home/HomeLayout/HomeLayout";

export default function Home() {
  return (
    <>
      <Head>
        <title>MOGAZOA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <main>메인 페이지</main> */}
      <HomeLayout />
    </>
  );
}
